[package]
name = "ttol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.14.2"
tracing = "0.1.32"
structopt = "0.3.25"
shiplift = "0.7"
toml = "0.5.8"
serde = "1.0"